### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shibataryohei** [Lifoof/MoGCN#3]
Hi,

Thank you so much for providing such a nice pipeline! I'm now running the code in Google Colab. `AE_run.py` and `SNF.py` were successfully done but `GCN_run.py` has failed with the following error message.
```
Traceback (most recent call last):
  File "/content/MoGCN/GCN_run.py", line 207, in <module>
    name = file.split('\\')[1]
IndexError: list index out of range
```
My current directory is "/content/MoGCN/". Is there any solution?

Best,
Rio

**Comment by Mohamedema** [comment]
@shibataryohei Same error, did you solve it?

**Comment by shibataryohei** [comment]
@Mohamedema Not yet. I've also sent an email to the author but not received a response. We should contact to the corresponding author.

**Comment by Lifoof** [comment]
It means the list after splitting does not have index "1". You can print the “file”in line 207 and check the path separator. Since this is a Windows project, the path separator used is '\'. Changing the separator of line 207 to ‘/’ may be effective.

**Comment by Lifoof** [comment]
It means the list after splitting does not have index "1". You can print the “file”in line 207 and check the path separator. Since this is a Windows project, the path separator used is '\'. Changing the separator of line 207 to ‘/’ may be effective.

**Comment by Lifoof** [comment]
It means the list after splitting does not have index "1". You can print the “file”in line 207 and check the path separator. Since this is a Windows project, the path separator used is '\\'. Changing the separator of line 207 to ‘/’ may be effective.

**Comment by shibataryohei** [comment]
@Lifoof

Thx for replying. After replacing '\\' --> ’/’ in line 207, I got new error messages as below.
```python
File "/content/MoGCN/GCN_run.py", line 208, in <module>
    epoch_nb = int(name.split('.')[0])
ValueError: invalid literal for int() with base 10: 'GCN'
```
Based on my understanding, the code in lines 204–211 should be revised into the following.
```python
            #reserve the best model, delete other models
            files = glob.glob('model/GCN/*.pkl')
            for file in files:
                name = file.split('/')[2]
                epoch_nb = int(name.split('.')[0])
                #print(file, name, epoch_nb)
                if epoch_nb != best_epoch:
                    os.remove(file)
```
Then, `GCN_run.py` has seemed to run successfully. Could you please verify if the results obtained are truly correct?

In addition, I found `GCN_predicted_data.csv` has only n = 68 data (= Sample_ID in `test_sample.csv`). How can we get the "prediction data" of non-test data (n = 511-68)? Or some errors has still occurred ?

Thank you,
Ryohei

**Comment by Lifoof** [comment]
I think the modifications you made are correct. 

This part of the code is designed to predict the samples in test_sample.csv. To obtain the "prediction data" for all samples, maybe you can try to modify the parameters(such as ‘idx’) of predict() in line 216. The above is my idea, and I have not tried it myself yet.

**Comment by shibataryohei** [comment]
@Lifoof Thank you so much! I'll try that way!

**Comment by Mohamedema** [comment]
If I understood this part of the code well, it only removes the unwanted model, so I put hash #from line 207 to 211 and it works.
